# Use the mandatory v2 schema
version: 2

# This hook runs BEFORE GoReleaser's main logic.
# We use it to build the Wails application for all platforms at once.
before:
  hooks:
    - bun install --cwd ./frontend
    # This single command cross-compiles for all target platforms.
    # Wails will create the .exe and .app bundles correctly.
    - wails build -clean -platform="linux/amd64,windows/amd64,darwin/universal" -ldflags="-s -w"

# This section tells GoReleaser where to find the pre-built binaries.
builds:
  - id: linux
    goos: [linux]
    goarch: [amd64]
    binary: "build/bin/{{ .ProjectName }}"
    skip: true

  - id: windows
    goos: [windows]
    goarch: [amd64]
    binary: "build/bin/{{ .ProjectName }}.exe"
    skip: true

  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: "build/bin/{{ .ProjectName }}.app"
    skip: true

# This section creates .zip and .tar.gz archives.
archives:
  - id: linux-archive
    # Use the new `ids` key to link to builds
    ids: [linux]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"

  - id: windows-archive
    ids: [windows]
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64"

  - id: macos-archive
    ids: [macos]
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_macos_universal"

nfpms:
  - id: linux-packages
    ids: [linux] # Use the new `ids` key
    formats: [deb, rpm]
    maintainer: "bethropolis@outlook.com"
    description: "A CHIP-8 emulator built with Wails."
    homepage: "https://github.com/bethropolis/chip8"
    license: MIT
    contents:
      - src: "build/bin/{{ .ProjectName }}"
        dst: "/usr/bin/{{ .ProjectName }}"
      - src: "build/linux/app.desktop"
        dst: "/usr/share/applications/{{ .ProjectName }}.desktop"
      - src: "build/linux/appicon.png"
        dst: "/usr/share/pixmaps/{{ .ProjectName }}.png"

checksum:
  name_template: "checksums.txt"

release:
  # GoReleaser will automatically generate a changelog from your commits.
  prerelease: auto
