# Use the mandatory v2 schema
version: 2
before:
  hooks:
    - bun install --cwd ./frontend
    - wails build -clean -tags webkit2_41 -platform="linux/amd64,windows/amd64,darwin/universal" -ldflags="-s -w"

# Reference the pre-built binaries
builds:
  - id: linux
    goos: [linux]
    goarch: [amd64]
    binary: "{{ .ProjectName }}"
    # Point to where Wails puts the Linux binary
    main: "./build/bin/{{ .ProjectName }}"
    skip: true

  - id: windows
    goos: [windows]
    goarch: [amd64]
    binary: "{{ .ProjectName }}"
    # Point to where Wails puts the Windows binary
    main: "./build/bin/{{ .ProjectName }}.exe"
    skip: true

  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: "{{ .ProjectName }}"
    # Point to where Wails puts the macOS app
    main: "./build/bin/{{ .ProjectName }}.app"
    skip: true

archives:
  - id: linux-archive
    ids: [linux]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"

  - id: windows-archive
    ids: [windows]
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64"

  - id: macos-archive
    ids: [macos]
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_macos_universal"

nfpms:
  - id: linux-packages
    ids: [linux]
    formats: [deb, rpm]
    maintainer: "bethropolis@outlook.com"
    description: "A CHIP-8 emulator built with Wails."
    homepage: "https://github.com/bethropolis/chip8"
    license: MIT
    contents:
      - src: "build/bin/{{ .ProjectName }}"
        dst: "/usr/bin/{{ .ProjectName }}"
      - src: "build/linux/app.desktop"
        dst: "/usr/share/applications/{{ .ProjectName }}.desktop"
      - src: "build/linux/appicon.png"
        dst: "/usr/share/pixmaps/{{ .ProjectName }}.png"

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
