project_name: chip8-wails
builds:
  - id: wails
    builder: prebuilt
    goos: [linux]
    goarch: [amd64]
    prebuilt:
      path: "build/bin/chip8-wails"
    binary: "chip8-wails"
nfpms:
  - id: linuxpkgs
    formats: [deb, rpm]
    maintainer: "bethropolis@outlook.com"
    bindir: /usr/bin
    # Use the binary built by wails-build-action
    contents:
      - src: ./build/bin/chip8-wails
        dst: /usr/bin/chip8-wails
        file_info:
          mode: 0755
release:
  github:
    owner: bethropolis
    name: chip8
