# Use the mandatory v2 schema
version: 2
before:
  hooks:
    - bun install --cwd ./frontend
    - wails build -clean -tags webkit2_41 -platform="linux/amd64,windows/amd64,darwin/universal" -ldflags="-s -w"

# Since we're using pre-built binaries, we don't need build configs
# GoReleaser will work with the archives and packages sections

# This section creates .zip and .tar.gz archives from pre-built binaries
archives:
  - id: linux-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"
    files:
      - "build/bin/{{ .ProjectName }}"
      - "build/linux/app.desktop"
      - "build/linux/appicon.png"

  - id: windows-archive
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64"
    files:
      - "build/bin/{{ .ProjectName }}.exe"

  - id: macos-archive
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_macos_universal"
    files:
      - "build/bin/{{ .ProjectName }}.app/**/*"

nfpms:
  - id: linux-packages
    formats: [deb, rpm]
    maintainer: "bethropolis@outlook.com"
    description: "A CHIP-8 emulator built with Wails."
    homepage: "https://github.com/bethropolis/chip8"
    license: MIT
    contents:
      - src: "build/bin/{{ .ProjectName }}"
        dst: "/usr/bin/{{ .ProjectName }}"
      - src: "build/linux/app.desktop"
        dst: "/usr/share/applications/{{ .ProjectName }}.desktop"
      - src: "build/linux/appicon.png"
        dst: "/usr/share/pixmaps/{{ .ProjectName }}.png"

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
