// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearBreakpoint(arg1:number):Promise<void>;

export function FrontendReady():Promise<void>;

export function GetDisplay():Promise<Array<number>>;

export function GetInitialState():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetMemory(arg1:number,arg2:number):Promise<string>;

export function GetROMs():Promise<Array<string>>;

export function HardReset():Promise<void>;

export function KeyDown(arg1:number):Promise<void>;

export function KeyUp(arg1:number):Promise<void>;

export function LoadROM(arg1:string):Promise<void>;

export function LoadState(arg1:Array<number>):Promise<void>;

export function LoadStateFromFile():Promise<void>;

export function PlayBeep():Promise<void>;

export function Reset():Promise<void>;

export function SaveScreenshot(arg1:string):Promise<void>;

export function SaveState():Promise<Array<number>>;

export function SaveStateToFile(arg1:Array<number>):Promise<void>;

export function SetBreakpoint(arg1:number):Promise<void>;

export function SetClockSpeed(arg1:number):Promise<void>;

export function SoftReset():Promise<void>;

export function TogglePause():Promise<boolean>;
