// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearBreakpoint(arg1) {
  return window['go']['main']['App']['ClearBreakpoint'](arg1);
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMemory(arg1, arg2) {
  return window['go']['main']['App']['GetMemory'](arg1, arg2);
}

export function GetROMs() {
  return window['go']['main']['App']['GetROMs']();
}

export function HardReset() {
  return window['go']['main']['App']['HardReset']();
}

export function KeyDown(arg1) {
  return window['go']['main']['App']['KeyDown'](arg1);
}

export function KeyUp(arg1) {
  return window['go']['main']['App']['KeyUp'](arg1);
}

export function LoadROM(arg1) {
  return window['go']['main']['App']['LoadROM'](arg1);
}

export function LoadROMByPath(arg1) {
  return window['go']['main']['App']['LoadROMByPath'](arg1);
}

export function LoadROMFromFile() {
  return window['go']['main']['App']['LoadROMFromFile']();
}

export function LoadStateFromFile() {
  return window['go']['main']['App']['LoadStateFromFile']();
}

export function OpenGitHubLink() {
  return window['go']['main']['App']['OpenGitHubLink']();
}

export function SaveScreenshot(arg1) {
  return window['go']['main']['App']['SaveScreenshot'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveStateToFile() {
  return window['go']['main']['App']['SaveStateToFile']();
}

export function SetBreakpoint(arg1) {
  return window['go']['main']['App']['SetBreakpoint'](arg1);
}

export function SetClockSpeed(arg1) {
  return window['go']['main']['App']['SetClockSpeed'](arg1);
}

export function ShowAboutDialog() {
  return window['go']['main']['App']['ShowAboutDialog']();
}

export function SoftReset() {
  return window['go']['main']['App']['SoftReset']();
}

export function StartDebugUpdates() {
  return window['go']['main']['App']['StartDebugUpdates']();
}

export function StopDebugUpdates() {
  return window['go']['main']['App']['StopDebugUpdates']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
