// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function ClearBreakpoint(arg1:number):Promise<void>;

export function GetInitialState():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetMemory(arg1:number,arg2:number):Promise<string>;

export function GetROMs():Promise<Array<string>>;

export function HardReset():Promise<void>;

export function KeyDown(arg1:number):Promise<void>;

export function KeyUp(arg1:number):Promise<void>;

export function LoadROM(arg1:string):Promise<void>;

export function LoadROMByPath(arg1:string):Promise<string>;

export function LoadROMFromFile():Promise<string>;

export function LoadStateFromFile():Promise<void>;

export function OpenGitHubLink():Promise<void>;

export function SaveScreenshot(arg1:string):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SaveStateToFile():Promise<void>;

export function SetBreakpoint(arg1:number):Promise<void>;

export function SetClockSpeed(arg1:number):Promise<void>;

export function ShowAboutDialog():Promise<void>;

export function SoftReset():Promise<void>;

export function StartDebugUpdates():Promise<void>;

export function StopDebugUpdates():Promise<void>;

export function TogglePause():Promise<boolean>;
